'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import type {User} from '@supabase/supabase-js';
import {ArrowDownRight,ArrowUpRight,CreditCard,Eye,EyeOff,Landmark,LayoutDashboard,LogOut,Plus,ReceiptText,RefreshCw,Search,Tag,Target,TrendingUp,WalletCards,type LucideIcon} from 'lucide-react';
import {money} from '@/lib/format';
import {getSupabase} from '@/lib/supabase/client';
import {loadData,errorText} from '@/lib/data';
import {accountBalance,cardBalance,emptyData,monthEnd,today,totals,type Data} from '@/lib/finance';
import {EntryForm,type Editing,type Table} from './EntryForm';
const sections:{name:string;icon:LucideIcon;table?:Table}[]=[{name:'Visão geral',icon:LayoutDashboard},{name:'Lançamentos',icon:ReceiptText,table:'transactions'},{name:'Contas',icon:Landmark,table:'accounts'},{name:'Cartões',icon:CreditCard,table:'credit_cards'},{name:'Categorias',icon:Tag,table:'categories'},{name:'Orçamento',icon:Target,table:'budgets'}];
const statusName:Record<string,string>={cleared:'Realizado',planned:'Previsto',pending:'Pendente',cancelled:'Cancelado'};
const kindName:Record<string,string>={income:'Receita',expense:'Despesa',transfer:'Transferência',card_payment:'Pagamento de cartão',both:'Receita e despesa'};
export function Dashboard({user}:{user:User}){
 const [active,setActive]=useState('Visão geral'),[month,setMonth]=useState(today().slice(0,7)),[hidden,setHidden]=useState(false),[search,setSearch]=useState('');
 const [households,setHouseholds]=useState<{id:string;name:string}[]>([]),[household,setHousehold]=useState(''),[data,setData]=useState<Data>(emptyData),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<Editing|null>(null);
 const request=useRef(0);
 const refresh=useCallback(async()=>{if(!household)return;const id=++request.current;setLoading(true);setError('');try{const d=await loadData(household);if(id===request.current)setData(d);}catch(e){if(id===request.current)setError(errorText(e));throw e;}finally{if(id===request.current)setLoading(false);}},[household]);
 useEffect(()=>{let mounted=true;getSupabase().from('households').select('id,name').order('created_at').then(({data,error})=>{if(!mounted)return;if(error)setError(errorText(error));else{setHouseholds(data||[]);setHousehold(data?.[0]?.id||'');}setLoading(Boolean(data?.length));});return()=>{mounted=false;};},[]);
 useEffect(()=>{if(!household)return;let mounted=true;const id=++request.current;loadData(household).then(d=>{if(mounted&&id===request.current)setData(d);}).catch(e=>{if(mounted)setError(errorText(e));}).finally(()=>{if(mounted)setLoading(false);});return()=>{mounted=false;};},[household]);
 async function setup(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const name=String(new FormData(event.currentTarget).get('name')||'Minhas finanças').trim();const {data,error}=await getSupabase().from('households').insert({owner_user_id:user.id,name}).select('id,name').single();if(error)throw error;setHouseholds([data]);setHousehold(data.id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function remove(table:Table,row:Record<string,unknown>){if(!window.confirm(table==='transactions'?'Cancelar este lançamento? Ele continuará no histórico.':'Arquivar este cadastro? O histórico será preservado.'))return;setBusy(true);setError('');try{const payload=table==='transactions'?{status:'cancelled'}:table==='budgets'?{amount:0}:{active:false};const {data,error}=await getSupabase().from(table).update(payload).eq('id',String(row.id)).eq('household_id',household).select('id');if(error)throw error;if(!data?.length)throw new Error('Registro não alterado.');await refresh();setNotice('Registro atualizado.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function logout(){setBusy(true);const {error}=await getSupabase().auth.signOut();if(error){setError(errorText(error));setBusy(false);}}
 const summary=useMemo(()=>totals(data,month),[data,month]);
 const chart=Array.from({length:6},(_,i)=>{const [year,m]=month.split('-').map(Number);const date=new Date(year,m-6+i,1);const key=date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0');return {date,key,...totals(data,key)};});
 const chartMax=Math.max(1,...chart.flatMap(t=>[t.income,t.expenses]));
 const display=(n:number)=>hidden?'R$ ••••••':money(n);
 const transactions=data.transactions.filter(t=>t.occurred_on.startsWith(month)&&`${t.description} ${data.categories.find(c=>c.id===t.category_id)?.name||''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).sort((a,b)=>b.occurred_on.localeCompare(a.occurred_on)||a.id.localeCompare(b.id));
 const selected=sections.find(s=>s.name===active)!;
 const rowActions=(table:Table,row:object)=><div className="rowActions"><button disabled={busy||loading} onClick={()=>setEditing({table,row:row as Record<string,unknown>})}>Editar</button><button disabled={busy||loading} onClick={()=>void remove(table,row as Record<string,unknown>)}>{table==='transactions'?'Cancelar':table==='budgets'?'Zerar':'Arquivar'}</button></div>;
 const txList=(limit?:number)=><div className="txList">{transactions.length===0?<div className="empty"><ReceiptText size={28}/><strong>Nenhum lançamento neste mês</strong><p>Adicione receitas e despesas para acompanhar seu dinheiro.</p><button className="secondary" onClick={()=>setEditing({table:'transactions'})}>Adicionar lançamento</button></div>:transactions.slice(0,limit).map(tx=><div className={`tx ${tx.status==='cancelled'?'cancelled':''}`} key={tx.id}><div className="txIcon">{tx.kind==='income'?<ArrowDownRight size={18}/>:tx.kind==='expense'?<ArrowUpRight size={18}/>:<RefreshCw size={18}/>}</div><div className="txText"><strong>{tx.description}</strong><small>{new Date(tx.occurred_on+'T12:00:00').toLocaleDateString('pt-BR')} · {kindName[tx.kind]} · {statusName[tx.status]}{tx.category_id&&` · ${data.categories.find(c=>c.id===tx.category_id)?.name||'Categoria'}`}</small></div><strong className={tx.kind==='income'?'txPositive':''}>{display(tx.amount)}</strong>{active==='Lançamentos'&&rowActions('transactions',tx)}</div>)}</div>;
 return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="brandMark">F</div><div><strong>Finanças</strong><span>Controle Financeiro</span></div></div><nav className="nav" aria-label="Navegação principal">{sections.map(({name,icon:Icon})=><button key={name} title={name} className={active===name?'active':''} aria-current={active===name?'page':undefined} onClick={()=>setActive(name)}><Icon size={19}/><span>{name}</span></button>)}</nav><div className="aiCard"><TrendingUp size={24}/><strong>Planeje com clareza</strong><p>Registre também o que ainda vai entrar e sair. Sua projeção acompanha cada lançamento.</p></div><div className="sidebarBottom"><button onClick={()=>void logout()} disabled={busy}><LogOut size={19}/>Sair da conta</button><div className="profile"><div>{String(user.user_metadata.display_name||user.email||'F').slice(0,2).toUpperCase()}</div><span><strong>{user.user_metadata.display_name||'Minha conta'}</strong><small>Espaço pessoal</small></span></div></div></aside>
 <main className="main"><header className="topbar"><div className="mobileBrand"><div className="brandMark">F</div><strong>Finanças</strong></div><div className="search"><Search size={18}/><input aria-label="Buscar lançamentos" placeholder="Buscar lançamento ou categoria…" value={search} onChange={e=>{setSearch(e.target.value);setActive('Lançamentos');}}/></div><div className="topActions"><button className="iconBtn" aria-label="Atualizar dados" disabled={loading||!household} onClick={()=>void refresh().catch(()=>{})}><RefreshCw size={18}/></button><button className="primary" disabled={!household||loading} onClick={()=>setEditing({table:'transactions'})}><Plus size={18}/><span>Novo lançamento</span></button><button className="mobileLogout iconBtn" aria-label="Sair da conta" onClick={()=>void logout()}><LogOut size={18}/></button></div></header>
 <section className="content"><div className="welcome"><div><p className="eyebrow">SEU ESPAÇO FINANCEIRO</p><h1>{active==='Visão geral'?'Seu dinheiro, sob controle.':active}</h1><p>{active==='Visão geral'?'Uma visão clara do presente e do que vem pela frente.':'Organize os detalhes das suas finanças.'}</p></div><label className="monthLabel">Mês<input type="month" aria-label="Mês de referência" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label></div>
 {households.length>1&&<label className="spaceSelect">Espaço financeiro<select value={household} onChange={e=>{request.current++;setLoading(true);setData(emptyData);setError('');setNotice('');setEditing(null);setHousehold(e.target.value);}}>{households.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label>}
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}>×</button></p>}
 {loading?<div className="empty" role="status">Carregando seus dados…</div>:!household?<article className="panel onboarding"><h2>Vamos organizar suas finanças?</h2><p>Crie seu espaço pessoal. Depois, adicione uma conta, suas categorias e o primeiro lançamento.</p><form onSubmit={setup}><label>Nome do espaço<input name="name" defaultValue="Minhas finanças" maxLength={100} required/></label><button className="primary" disabled={busy||Boolean(error)}>{busy?'Criando…':'Criar meu espaço'}</button></form></article>:<>
 <nav className="mobileNav" aria-label="Seções">{sections.map(s=><button key={s.name} className={s.name===active?'active':''} onClick={()=>setActive(s.name)}>{s.name}</button>)}</nav>
 {active==='Visão geral'?<><div className="heroGrid"><article className="balanceCard"><div className="cardHead"><span>Saldo em contas</span><button aria-label={hidden?'Mostrar valores':'Ocultar valores'} onClick={()=>setHidden(!hidden)}>{hidden?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><div className="bigValue">{display(summary.balance)}</div><p className="balanceNote">Saldos iniciais + movimentações realizadas</p><div className="balanceFooter"><div><small>Saldo projetado no fim do mês</small><strong>{display(summary.projected)}</strong></div><TrendingUp size={36}/></div></article><article className="metricCard"><div className="metricIcon income"><ArrowDownRight size={19}/></div><span>Receitas do mês</span><strong>{display(summary.income)}</strong><small>Realizadas e previstas</small></article><article className="metricCard"><div className="metricIcon expense"><ArrowUpRight size={19}/></div><span>Despesas do mês</span><strong>{display(summary.expenses)}</strong><small>Inclui compras no cartão; exclui pagamentos de fatura</small></article></div>
 <div className="insight"><div className="insightIcon"><TrendingUp size={20}/></div><div><strong>{data.transactions.length===0?'Seu planejamento começa pelo primeiro lançamento.':summary.projected<0?'A projeção indica um saldo negativo.':'Acompanhe o que está previsto para este mês.'}</strong><p>A projeção considera lançamentos até o fim do mês e desconta todo o saldo de compras no cartão ainda não coberto por pagamentos, independentemente do vencimento. Não é uma previsão de IA.</p></div></div>
 <div className="bodyGrid"><article className="panel"><div className="panelTitle"><div><span>Fluxo financeiro</span><small>Últimos seis meses · realizados e previstos</small></div></div><div className="flowChart">{chart.map(t=>{const {key,date:d}=t;const max=chartMax;return <div className="flowColumn" key={key}><div className="flowBars" aria-label={`${key}: receitas ${display(t.income)}, despesas ${display(t.expenses)}`}><i title={display(t.income)} style={{height:`${hidden?0:t.income/max*100}%`}}/><i title={display(t.expenses)} style={{height:`${hidden?0:t.expenses/max*100}%`}}/></div><span>{d.toLocaleDateString('pt-BR',{month:'short'})}</span></div>;})}</div><div className="legend"><span><i className="lgIncome"/>Receitas</span><span><i className="lgExpense"/>Despesas</span></div></article><article className="panel budgetPanel"><div className="panelTitle"><div><span>Orçamento do mês</span><small>Limites por categoria</small></div><button onClick={()=>setActive('Orçamento')}>Gerenciar</button></div><div className="budgetSummary"><strong>{display(summary.budget)}</strong><span>Limite cadastrado</span><p>{summary.budget>0?`${Math.round(summary.expenses/summary.budget*100)}% em despesas totais`:'Defina limites para acompanhar seus gastos.'}</p></div><button className="secondary" onClick={()=>setEditing({table:'budgets'})}>Definir orçamento</button></article></div><div className="lowerGrid"><article className="panel transactions"><div className="panelTitle"><div><span>Últimos lançamentos</span><small>No mês selecionado</small></div><button onClick={()=>setActive('Lançamentos')}>Ver todos</button></div>{txList(6)}</article><article className="panel"><div className="panelTitle"><div><span>Cartões</span><small>Compras menos pagamentos acumulados</small></div><button onClick={()=>setActive('Cartões')}>Gerenciar</button></div>{data.credit_cards.length===0?<div className="empty"><WalletCards size={28}/><p>Cadastre seu primeiro cartão.</p><button className="secondary" onClick={()=>setEditing({table:'credit_cards'})}>Adicionar cartão</button></div>:data.credit_cards.map(c=><div className="creditRow" key={c.id}><div className="miniCard"><CreditCard size={20}/></div><div className="creditInfo"><strong>{c.name}</strong><div className="creditAmounts"><strong>{display(cardBalance(data,c.id,monthEnd(month)))}</strong><span>Limite {display(c.credit_limit)}</span></div></div></div>)}</article></div></>:<article className="panel"><div className="panelTitle"><div><span>{active}</span><small>{active==='Lançamentos'?'Receitas, despesas, transferências e pagamentos':'Cadastros do seu espaço financeiro'}</small></div><button className="secondary" onClick={()=>setEditing({table:selected.table!})}><Plus size={16}/>Adicionar</button></div>
 {active==='Lançamentos'&&<><input className="mobileSearch" aria-label="Filtrar lançamentos" placeholder="Buscar lançamento…" value={search} onChange={e=>setSearch(e.target.value)}/>{txList()}</>}
 {active==='Contas'&&<div className="recordGrid">{data.accounts.map(a=><div className="recordCard" key={a.id}><Landmark size={23}/><h3>{a.name} {!a.active&&<small>Arquivada</small>}</h3><p>{a.institution||'Conta pessoal'}</p><strong>{display(accountBalance(data,a))}</strong><small>Saldo atual · inicial {display(a.opening_balance)}</small>{rowActions('accounts',a)}</div>)}</div>}
 {active==='Cartões'&&<div className="recordGrid">{data.credit_cards.map(c=><div className="recordCard" key={c.id}><CreditCard size={23}/><h3>{c.name} {!c.active&&<small>Arquivado</small>}</h3><p>{c.last4?`•••• ${c.last4}`:'Cartão de crédito'} · Vence dia {c.due_day}</p><strong>{display(cardBalance(data,c.id,monthEnd(month)))}</strong><small>Compras menos pagamentos até o fim do mês</small><p>Limite {display(c.credit_limit)} · Fecha dia {c.closing_day}</p>{rowActions('credit_cards',c)}</div>)}</div>}
 {active==='Categorias'&&<div className="recordGrid">{data.categories.map(c=><div className="recordCard" key={c.id}><Tag size={23}/><h3>{c.name}</h3><p>{kindName[c.kind]} {!c.active&&'· Arquivada'}</p>{rowActions('categories',c)}</div>)}</div>}
 {active==='Orçamento'&&<div className="recordGrid">{data.budgets.filter(b=>b.month.startsWith(month)).map(b=>{const spent=data.transactions.filter(t=>t.category_id===b.category_id&&t.kind==='expense'&&t.status!=='cancelled'&&t.occurred_on.startsWith(month)).reduce((n,t)=>n+Number(t.amount),0);return <div className="recordCard" key={b.id}><Target size={23}/><h3>{data.categories.find(c=>c.id===b.category_id)?.name||'Categoria'}</h3><strong>{display(spent)} <small>de {display(b.amount)}</small></strong><progress max={Math.max(Number(b.amount),spent,1)} value={spent}/><p>{spent>b.amount?'Limite ultrapassado':'Disponível'}: {display(Math.abs(Number(b.amount)-spent))}</p>{rowActions('budgets',b)}</div>;})}</div>}
 {selected.table&&(selected.table==='budgets'?data.budgets.filter(b=>b.month.startsWith(month)):data[selected.table]).length===0&&active!=='Lançamentos'&&<div className="empty"><selected.icon size={32}/><strong>Comece seu cadastro</strong><p>Use Adicionar para criar o primeiro registro.</p></div>}
 </article>}
 </>}
 </section></main>{editing&&<EntryForm editing={editing} data={data} household={household} month={month} onClose={()=>setEditing(null)} onSaved={async()=>{await refresh();setNotice('Registro salvo com sucesso.');}}/>}</div>;
}
